# Generated by Django 3.1.4 on 2020-12-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201210_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='flag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='built',
            field=models.DateField(blank=True, null=True),
        ),
    ]
