# Generated by Django 3.1.4 on 2020-12-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201210_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='account',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='team',
        ),
        migrations.RemoveField(
            model_name='sailor',
            name='account',
        ),
        migrations.RemoveField(
            model_name='team',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='sailor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.sailor'),
        ),
        migrations.AddField(
            model_name='account',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='boat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.boat'),
            preserve_default=False,
        ),
    ]
