# Generated by Django 3.1.4 on 2020-12-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201210_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='soruce_id',
            new_name='source_id',
        ),
    ]
