# Generated by Django 3.1.4 on 2020-12-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201211_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
