# Generated by Django 3.1.4 on 2020-12-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_boat_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
