# Generated by Django 3.1.4 on 2020-12-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
