# Generated by Django 3.1.4 on 2020-12-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20201225_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.SlugField(max_length=100),
        ),
    ]
