# Generated by Django 3.1.4 on 2020-12-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20201225_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='races',
            new_name='events',
        ),
    ]
